name: Example Workflow
on:
  workflow_dispatch:
jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v2
      - name: Load secret
        uses: 1password/load-secrets-action@6d1c2654be9ad019ca5c3839a61e91f6f1c10635 # v1
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          SECRET: op://infra/Test1password/credential
      - name: Use Secret
        run: echo "Secret value is $SECRET"
